{
 "title": "snarkOS v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "states of current connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "snarkos_peers_connected_total", "legendFormat": "connected" },
    { "expr": "snarkos_peers_candidate_total", "legendFormat": "disconnected" },
    { "expr": "snarkos_peers_restricted_total", "legendFormat": "connecting" }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "snarkos_blocks_height_total", "legendFormat": "block height" }
   ]
  },
  {
   "title": "Internal RTT for request/response cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(snarkos_internal_rtt_ping_sum[$__rate_interval])/rate(snarkos_internal_rtt_ping_count[$__rate_interval])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(snarkos_internal_rtt_pong_sum[$__rate_interval])/rate(snarkos_internal_rtt_pong_count[$__rate_interval])",
     "legendFormat": "pong (processing, no response)"
    },
    {
     "expr": "rate(snarkos_internal_rtt_peers_request_sum[$__rate_interval])/rate(snarkos_internal_rtt_peers_request_count[$__rate_interval])",
     "legendFormat": "peers_request"
    },
    {
     "expr": "rate(snarkos_internal_rtt_block_request_sum[$__rate_interval])/rate(snarkos_internal_rtt_block_request_count[$__rate_interval])",
     "legendFormat": "block_request"
    }
   ]
  }
 ]
}