[package]
name = "snarkos-node-sync-locators"
version = "3.0.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Locators to synchronize a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoNet/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "cryptography::cryptocurrencies", "os" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]
test = [ ]

[dependencies.anyhow]
version = "1.0"

[dependencies.indexmap]
version = "2.1"
features = [ "serde", "rayon" ]

[dependencies.serde]
version = "1"

[dependencies.snarkvm]
workspace = true

[dependencies.tracing]
version = "0.1"
